name: 'Setup rust'
description: 'Rust setup, including cache configuration'
inputs:
  targets:
    description: 'Cargo target'
    required: true
  components:
    description: 'Rustup components'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
      env:
        CARGO_INCREMENTAL: '1'

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/
          ~/.cargo/git/db/
          ~/.napi-rs
          target/${{ inputs.target }}
        key: stable-${{ inputs.target }}-cargo-cache
