/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsWebpEncoderOptions {
  lossless?: boolean
  quality?: number
  method?: number
  loopCount?: number
}
export type JsWebpEncoder = WebpEncoder
export declare class WebpEncoder {
  constructor(width: number, height: number, outputPath: string, options?: JsWebpEncoderOptions | undefined | null)
  addFrame(frameData: Buffer, duration: number): void
  finish(duration: number): void
}
