/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class WebpEncoder {
  constructor(width: number, height: number)
  setFrameRate(frameRate: number): void
  addFrame(frameData: Buffer, duration?: number): void
  getBuffer(options?: WebpEncoderOptions): Promise<Buffer>
  getBufferSync(options?: WebpEncoderOptions): Buffer
  writeToFile(path: string, options?: WebpEncoderOptions): Promise<Buffer>
  writeToFileSync(path: string, options?: WebpEncoderOptions): Buffer
  clearFrames(): void
  setDimensions(width: number, height: number): void
}
export type JsWebpEncoder = WebpEncoder

export interface DecodedWebp {
  width: number
  height: number
  frames: Array<WebpFrame>
}

export declare function decodeWebp(buffer: Buffer): DecodedWebp

export interface WebpEncoderOptions {
  lossless?: boolean
  quality?: number
  loopCount?: number
}

export interface WebpFrame {
  data: Buffer
  timestamp: number
}
