/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsWebpEncoderOptions {
  lossless?: boolean
  quality?: number
  method?: number
  loopCount?: number
}
export type JsWebpEncoder = WebpEncoder
export declare class WebpEncoder {
  constructor(width: number, height: number, options?: JsWebpEncoderOptions)
  setFrameRate(frameRate: number): void
  addFrame(frameData: Buffer, duration?: number): void
  getBuffer(): Buffer
  writeToFile(path: string): void
  clearFrames(): void
  setDimensions(width: number, height: number): void
  setOptions(options: JsWebpEncoderOptions): void
}
